//Problem
    
    /*You are given two strings s and t.
    
    String t is generated by random shuffling string s and then add one more letter at a random position.
    
    Return the letter that was added to t.
    
     
    
    Example 1:
    
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.
    Example 2:
    
    Input: s = "", t = "y"
    Output: "y"
     
    
    Constraints:
    
    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.*/

//Solution

class Solution {
    public char findTheDifference(String s, String t) {
        int[] arr = new int[26];

        for(int i = 0; i < s.length(); i++){
            char ch = s.charAt(i);
            arr[ch - 'a']--;
        }

        for(int i = 0; i < t.length(); i++){
            char ch = t.charAt(i);
            arr[ch - 'a']++;
        }

        for(int i = 0; i < 26; i++){
            if(arr[i] == 1){
                char ans = (char)(i + 97);
                return ans;
            }
        }

        return 'a';
    }
}
